# Generated by Django 3.2.4 on 2021-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
